# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cache
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - name: install
      run: yarn install
    - name: build blog
      run: yarn build
    - name: GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSHKEY }}
        name: id_rsa # optional
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: Compress
      run: tar -cvf /tmp/blog.tar ./public
    - name: scp-pipeline
      uses: cross-the-world/scp-pipeline@v1.2.1
      with:
        # ssh remote host
        host: www.tpfuture.top
        # ssh remote user
        user: ngmng
        # content of ssh private key. ex raw content of ~/.ssh/id_rsa
        key: ~/.ssh/id_rsa
        # connection timeout to remote host
        connect_timeout: 1000s
        # source to copy
        local: /tmp/blog.tar
        # destination for copy
        remote: /tmp/blog.tar
    - name: Deploy
      env:
        HOST: www.tpfuture.top
        USER: ngmng
      run: |
        tar xvf /tmp/blog.tar /home/ngmng/dist/
    
