# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install
      run: yarn install
    - name: build blog
      run: yarn build
    - name: GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSHKEY }}
        name: id_rsa # optional
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: Compress
      run: tar Jcf /tmp/blog.tar.xz ./public
    - name: upload
      run: node upload.js
    - name: ls -a via ssh
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: tar -xf /tmp/blog.tar.xz -C /tmp/&&rm -rf /home/ngmng/data/dist/&&ls -al /tmp&&ls -al /home/ngmng/data/&&mv /tmp/public/ /home/ngmng/data/dist/&&ls -al /home/ngmng/data/
        host: www.tpfuture.top
        username: ngmng
        privateKey: ${{ secrets.NGMNG_SSH_KEY }}
